### ISSUE TITLE
Compatibility with News, Music apps

### ISSUE THREAD

**Issue by avidwriter** [thealpa/SaneSideButtons#6]
This fork as well as the original code does not work in the Apple News or Music apps.

- macOS 12.5
- Corsair Harpoon wireless
- enabled in Accessibility and menubar

thanks!

**Comment by thealpa** [comment]
The way SaneSideButtons as well as SensibleSideButtons work is by simulating a three finger swipe whenever the side buttons on your mouse are pressed. Apps to be supported by SaneSideButtons therefore need to support trackpad gestures. Unfortunately some apps like Music (and previously iTunes) haven't supported trackpad gestures for years..
