### ISSUE TITLE
VS Code Support

### ISSUE THREAD

**Issue by FilipeMarch** [thealpa/SaneSideButtons#7]
The side buttons don't work on VS Code 😢
There'll be any support?

**Comment by thealpa** [comment]
The way SaneSideButtons as well as SensibleSideButtons work is by simulating a three finger swipe whenever the side buttons on your mouse are pressed. Apps to be supported by SaneSideButtons therefore need to support trackpad gestures. As it stands there was support for trackpad gestures in VS Code a couple of years ago, but unfortunately it looks like it was [broken by some Electron update](https://github.com/microsoft/vscode/issues/57629).

There is a [Swipe To Navigate Extension](https://marketplace.visualstudio.com/items?itemName=Seivan.swipe-to-navigate) for VS Code that you could check out and test. If you do please report back and I'll update the README.md for others who encounter this issue 🙂

**Comment by thealpa** [comment]
I've published an [alpha build](https://github.com/thealpa/SaneSideButtons/releases/tag/1.2.0-alpha) with support for disabling SaneSideButtons in certain applications such as Visual Studio Code. Please let me know if this solves your issue!

**Comment by amalrajan** [comment]
@thealpa the 1.2.0 beta release works perfectly for ignoring vs code. Thank you for this awesome app!
I tried the swipe to navigate extension though, it did not work.

**Comment by thealpa** [comment]
Glad 1.2.0 works for you! I'm closing the issue since 1.2.0 is now released.

**Comment by dkaplan111** [comment]
How do I go about ignoring apps? I can't seem to find the option? @thealpa

**Comment by thealpa** [comment]
@dkaplan111 Open the SaneSideButtons menu bar while the app you want to ignore is in the foreground. Check "Ignore YourApplication".
