### ISSUE TITLE
Some interference with Smooze Pro

### ISSUE THREAD

**Issue by Vinski** [thealpa/SaneSideButtons#8]
It seems that Sanesidebuttons is interfering with Smooze Pro. I have tried to adjust " Trigger on Mouse Down" setting, but this did not fix the problem.

The problem I'm having is that on Windows, ⌥Right & ⌥Left are used for Back & Forward, so I'm using Smooze Pro to bind these to my mouse side buttons for specific apps, like Remote Desktop Manager. But this does not work if SaneSideButton is enabled, it overrides Smooze Pro bindings. 

Can SaneSideButtones be disabled for specific apps?

**Comment by thealpa** [comment]
I've published an [alpha build](https://github.com/thealpa/SaneSideButtons/releases/tag/1.2.0-alpha) with support for disabling SaneSideButtons in certain applications. Please let me know how it works for you!

**Comment by Vinski** [comment]
I'm using alpha build now and "ignore app" feature is working and fixed interference, awesome!
